import { existsSync, mkdirSync, realpathSync, writeFileSync } from "node:fs"
import { isAbsolute, join, normalize, relative, resolve } from "node:path"
import type { DocHistoryMode } from "./types.js"

const DOC_HISTORY_MODES: DocHistoryMode[] = ["overwrite", "append-dated", "new-dated-file", "overwrite-archive"]
const DOCS_HISTORY_TIMESTAMP_REGEX = /^\d{4}-\d{2}-\d{2}T\d{2}-\d{2}-\d{2}Z$/

const README_CONTENT =
  "# Documentation\n\nThis directory contains project documentation artifacts generated by Wunderkind agents.\n"

function padTimestampPart(value: number): string {
  return value.toString().padStart(2, "0")
}

function splitMarkdownFilename(filename: string): { basename: string; extension: string } {
  if (!filename.endsWith(".md")) {
    throw new Error("Managed docs filenames must end with .md")
  }

  return {
    basename: filename.slice(0, -3),
    extension: ".md",
  }
}

export function formatDocsHistoryTimestamp(date: Date): string {
  return `${date.getUTCFullYear()}-${padTimestampPart(date.getUTCMonth() + 1)}-${padTimestampPart(date.getUTCDate())}T${padTimestampPart(date.getUTCHours())}-${padTimestampPart(date.getUTCMinutes())}-${padTimestampPart(date.getUTCSeconds())}Z`
}

export function buildAppendDatedHeading(timestamp: string, occurrence: number = 1): string {
  if (!DOCS_HISTORY_TIMESTAMP_REGEX.test(timestamp)) {
    throw new Error("timestamp must match YYYY-MM-DDTHH-mm-ssZ")
  }

  if (occurrence < 1) {
    throw new Error("occurrence must be at least 1")
  }

  const suffix = occurrence === 1 ? "" : ` (${occurrence})`
  return `## Update ${timestamp}${suffix}`
}

export function buildNewDatedFilename(canonicalFilename: string, timestamp: string, occurrence: number = 1): string {
  if (!DOCS_HISTORY_TIMESTAMP_REGEX.test(timestamp)) {
    throw new Error("timestamp must match YYYY-MM-DDTHH-mm-ssZ")
  }

  if (occurrence < 1) {
    throw new Error("occurrence must be at least 1")
  }

  const { basename, extension } = splitMarkdownFilename(canonicalFilename)
  const suffix = occurrence === 1 ? "" : `--${occurrence}`

  return `${basename}--${timestamp}${suffix}${extension}`
}

export function isManagedDocsFamilyFilename(canonicalFilename: string, candidateFilename: string): boolean {
  const { basename, extension } = splitMarkdownFilename(canonicalFilename)
  const escapedBasename = basename.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
  const escapedExtension = extension.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
  const familyPattern = new RegExp(`^${escapedBasename}--\\d{4}-\\d{2}-\\d{2}T\\d{2}-\\d{2}-\\d{2}Z(?:--\\d+)?${escapedExtension}$`)

  return familyPattern.test(candidateFilename)
}

export function validateDocsPath(docsPath: string): { valid: boolean; error?: string } {
  const normalizedInput = docsPath.replaceAll("\\", "/")

  if (isAbsolute(docsPath)) {
    return { valid: false, error: "docsPath must be a relative path" }
  }

  if (normalizedInput.startsWith("../") || normalizedInput.includes("/../") || normalizedInput === "..") {
    return { valid: false, error: "docsPath must not traverse parent directories" }
  }

  return { valid: true }
}

export function resolveProjectLocalDocsPath(docsPath: string, cwd: string): {
  docsPath: string
  absolutePath: string
} {
  const validation = validateDocsPath(docsPath)
  if (!validation.valid) {
    throw new Error(validation.error ?? "Invalid docsPath")
  }

  const normalizedDocsPath = normalize(docsPath.trim() === "" ? "./docs" : docsPath.trim())
  const projectRoot = realpathSync(cwd)
  const absolutePath = resolve(projectRoot, normalizedDocsPath)
  const relativeToRoot = relative(projectRoot, absolutePath)

  if (relativeToRoot === "" || relativeToRoot.startsWith("..") || isAbsolute(relativeToRoot)) {
    throw new Error("docsPath must resolve inside the current project root")
  }

  return {
    docsPath: normalizedDocsPath.endsWith("/") ? normalizedDocsPath.slice(0, -1) : normalizedDocsPath,
    absolutePath,
  }
}

export function validateDocHistoryMode(mode: string): mode is DocHistoryMode {
  return DOC_HISTORY_MODES.includes(mode as DocHistoryMode)
}

export function bootstrapDocsReadme(docsPath: string, cwd: string): void {
  const normalizedDocsPath = normalize(docsPath)
  const docsDir = join(cwd, normalizedDocsPath)
  const readmePath = join(docsDir, "README.md")

  mkdirSync(docsDir, { recursive: true })

  if (!existsSync(readmePath)) {
    writeFileSync(readmePath, README_CONTENT)
  }
}

export function getDocsEnabledPromptMessage(): string {
  return "Enable docs output to disk?"
}

export function getDocsPathPromptMessage(): string {
  return "Docs output directory path (relative to project root):"
}

export function getDocHistoryModePromptMessage(): string {
  return "Docs history mode"
}
