import { existsSync, mkdirSync, realpathSync, writeFileSync } from "node:fs"
import { isAbsolute, join, normalize, relative, resolve } from "node:path"
import type { DocHistoryMode } from "./types.js"

const DOC_HISTORY_MODES: DocHistoryMode[] = ["overwrite", "append-dated", "new-dated-file", "overwrite-archive"]

const README_CONTENT =
  "# Documentation\n\nThis directory contains project documentation artifacts generated by Wunderkind agents.\n"

export function validateDocsPath(docsPath: string): { valid: boolean; error?: string } {
  const normalizedInput = docsPath.replaceAll("\\", "/")

  if (isAbsolute(docsPath)) {
    return { valid: false, error: "docsPath must be a relative path" }
  }

  if (normalizedInput.startsWith("../") || normalizedInput.includes("/../") || normalizedInput === "..") {
    return { valid: false, error: "docsPath must not traverse parent directories" }
  }

  return { valid: true }
}

export function resolveProjectLocalDocsPath(docsPath: string, cwd: string): {
  docsPath: string
  absolutePath: string
} {
  const validation = validateDocsPath(docsPath)
  if (!validation.valid) {
    throw new Error(validation.error ?? "Invalid docsPath")
  }

  const normalizedDocsPath = normalize(docsPath.trim() === "" ? "./docs" : docsPath.trim())
  const projectRoot = realpathSync(cwd)
  const absolutePath = resolve(projectRoot, normalizedDocsPath)
  const relativeToRoot = relative(projectRoot, absolutePath)

  if (relativeToRoot === "" || relativeToRoot.startsWith("..") || isAbsolute(relativeToRoot)) {
    throw new Error("docsPath must resolve inside the current project root")
  }

  return {
    docsPath: normalizedDocsPath.endsWith("/") ? normalizedDocsPath.slice(0, -1) : normalizedDocsPath,
    absolutePath,
  }
}

export function validateDocHistoryMode(mode: string): mode is DocHistoryMode {
  return DOC_HISTORY_MODES.includes(mode as DocHistoryMode)
}

export function bootstrapDocsReadme(docsPath: string, cwd: string): void {
  const normalizedDocsPath = normalize(docsPath)
  const docsDir = join(cwd, normalizedDocsPath)
  const readmePath = join(docsDir, "README.md")

  mkdirSync(docsDir, { recursive: true })

  if (!existsSync(readmePath)) {
    writeFileSync(readmePath, README_CONTENT)
  }
}

export function getDocsEnabledPromptMessage(): string {
  return "Enable docs output to disk?"
}

export function getDocsPathPromptMessage(): string {
  return "Docs output directory path (relative to project root):"
}

export function getDocHistoryModePromptMessage(): string {
  return "Docs history mode"
}
