import { lstatSync, mkdirSync, realpathSync, renameSync, writeFileSync } from "node:fs"
import { isAbsolute, join, normalize, relative, resolve } from "node:path"
import type { DocHistoryMode } from "./types.js"

const DOC_HISTORY_MODES: DocHistoryMode[] = ["overwrite", "append-dated", "new-dated-file", "overwrite-archive"]
const DOCS_HISTORY_TIMESTAMP_REGEX = /^\d{4}-\d{2}-\d{2}T\d{2}-\d{2}-\d{2}Z$/

const README_CONTENT =
  "# Documentation\n\nThis directory contains project documentation artifacts generated by Wunderkind agents.\n"

function padTimestampPart(value: number): string {
  return value.toString().padStart(2, "0")
}

function splitMarkdownFilename(filename: string): { basename: string; extension: string } {
  if (!filename.endsWith(".md")) {
    throw new Error("Managed docs filenames must end with .md")
  }

  return {
    basename: filename.slice(0, -3),
    extension: ".md",
  }
}

export function formatDocsHistoryTimestamp(date: Date): string {
  return `${date.getUTCFullYear()}-${padTimestampPart(date.getUTCMonth() + 1)}-${padTimestampPart(date.getUTCDate())}T${padTimestampPart(date.getUTCHours())}-${padTimestampPart(date.getUTCMinutes())}-${padTimestampPart(date.getUTCSeconds())}Z`
}

export function buildAppendDatedHeading(timestamp: string, occurrence: number = 1): string {
  if (!DOCS_HISTORY_TIMESTAMP_REGEX.test(timestamp)) {
    throw new Error("timestamp must match YYYY-MM-DDTHH-mm-ssZ")
  }

  if (occurrence < 1) {
    throw new Error("occurrence must be at least 1")
  }

  const suffix = occurrence === 1 ? "" : ` (${occurrence})`
  return `## Update ${timestamp}${suffix}`
}

export function buildNewDatedFilename(canonicalFilename: string, timestamp: string, occurrence: number = 1): string {
  if (!DOCS_HISTORY_TIMESTAMP_REGEX.test(timestamp)) {
    throw new Error("timestamp must match YYYY-MM-DDTHH-mm-ssZ")
  }

  if (occurrence < 1) {
    throw new Error("occurrence must be at least 1")
  }

  const { basename, extension } = splitMarkdownFilename(canonicalFilename)
  const suffix = occurrence === 1 ? "" : `--${occurrence}`

  return `${basename}--${timestamp}${suffix}${extension}`
}

export function isManagedDocsFamilyFilename(canonicalFilename: string, candidateFilename: string): boolean {
  const { basename, extension } = splitMarkdownFilename(canonicalFilename)
  const escapedBasename = basename.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
  const escapedExtension = extension.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
  const familyPattern = new RegExp(`^${escapedBasename}--\\d{4}-\\d{2}-\\d{2}T\\d{2}-\\d{2}-\\d{2}Z(?:--\\d+)?${escapedExtension}$`)

  return familyPattern.test(candidateFilename)
}

export function validateDocsPath(docsPath: string): { valid: boolean; error?: string } {
  const trimmed = docsPath.trim()
  const rawInput = trimmed.replaceAll("\\", "/")
  const normalizedInput = normalize(trimmed === "" ? "./docs" : trimmed).replaceAll("\\", "/")

  if (isAbsolute(docsPath)) {
    return { valid: false, error: "docsPath must be a relative path" }
  }

  if (rawInput.startsWith("../") || rawInput.includes("/../") || rawInput === "..") {
    return { valid: false, error: "docsPath must not traverse parent directories" }
  }

  if (normalizedInput === "." || normalizedInput === "./") {
    return { valid: false, error: "docsPath must resolve inside the current project root" }
  }

  return { valid: true }
}

export function ensureDocsPathHasNoSymlinkSegments(docsPath: string, cwd: string): void {
  const normalizedDocsPath = normalize(docsPath.trim() === "" ? "./docs" : docsPath.trim())
  const segments = normalizedDocsPath.replaceAll("\\", "/").split("/").filter((segment) => segment.length > 0 && segment !== ".")
  let currentPath = cwd

  for (const segment of segments) {
    currentPath = join(currentPath, segment)

    const stat = lstatOrMissing(currentPath)
    if (stat === undefined) {
      return
    }

    if (stat.isSymbolicLink() || !stat.isDirectory()) {
      throw new Error("docs-output lane must not include symlinked segments")
    }
  }
}

function lstatOrMissing(path: string): ReturnType<typeof lstatSync> | undefined {
  try {
    return lstatSync(path)
  } catch (error) {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") return undefined
    throw error
  }
}

export function resolveProjectLocalDocsPath(docsPath: string, cwd: string): {
  docsPath: string
  absolutePath: string
} {
  const validation = validateDocsPath(docsPath)
  if (!validation.valid) {
    throw new Error(validation.error ?? "Invalid docsPath")
  }

  const normalizedDocsPath = normalize(docsPath.trim() === "" ? "./docs" : docsPath.trim())
  const projectRoot = realpathSync(cwd)
  const absolutePath = resolve(projectRoot, normalizedDocsPath)
  const relativeToRoot = relative(projectRoot, absolutePath)

  if (relativeToRoot === "" || relativeToRoot.startsWith("..") || isAbsolute(relativeToRoot)) {
    throw new Error("docsPath must resolve inside the current project root")
  }

  ensureDocsPathHasNoSymlinkSegments(normalizedDocsPath, cwd)

  return {
    docsPath: normalizedDocsPath.endsWith("/") ? normalizedDocsPath.slice(0, -1) : normalizedDocsPath,
    absolutePath,
  }
}

export function validateProjectLocalDocsPath(docsPath: string, cwd: string): { readonly valid: boolean; readonly error?: string } {
  const lexicalValidation = validateDocsPath(docsPath)
  if (!lexicalValidation.valid) return lexicalValidation

  try {
    const resolvedDocsPath = resolveProjectLocalDocsPath(docsPath, cwd).docsPath
    if (resolvedDocsPath === "DESIGN.md" || resolvedDocsPath.startsWith("DESIGN.md/")) {
      return { valid: false, error: "docsPath is invalid for docs-output because DESIGN.md is reserved for design-md" }
    }
  } catch (error) {
    return { valid: false, error: error instanceof Error ? error.message : "Invalid docsPath" }
  }

  return { valid: true }
}

export function validateDocsBootstrapLane(docsPath: string, cwd: string): void {
  const resolved = resolveProjectLocalDocsPath(docsPath, cwd)
  const docsDirectory = lstatOrMissing(resolved.absolutePath)
  if (docsDirectory !== undefined && (docsDirectory.isSymbolicLink() || !docsDirectory.isDirectory())) {
    throw new Error("docs-output lane must be a physical directory")
  }
  const readme = lstatOrMissing(join(resolved.absolutePath, "README.md"))
  if (readme !== undefined && (readme.isSymbolicLink() || !readme.isFile())) {
    throw new Error("docs-output README must be a physical regular file")
  }
}

export function validateDocHistoryMode(mode: string): mode is DocHistoryMode {
  return DOC_HISTORY_MODES.includes(mode as DocHistoryMode)
}

export function bootstrapDocsReadme(docsPath: string, cwd: string): void {
  validateDocsBootstrapLane(docsPath, cwd)
  const normalizedDocsPath = resolveProjectLocalDocsPath(docsPath, cwd).docsPath
  const docsDir = join(cwd, normalizedDocsPath)
  const readmePath = join(docsDir, "README.md")

  mkdirSync(docsDir, { recursive: true })
  validateDocsBootstrapLane(docsPath, cwd)

  const readme = lstatOrMissing(readmePath)
  if (readme !== undefined) {
    if (readme.isSymbolicLink() || !readme.isFile()) throw new Error("docs-output README must be a physical regular file")
    return
  }
  const temporary = `${readmePath}.wunderkind-${process.pid}-${Date.now()}.tmp`
  writeFileSync(temporary, README_CONTENT, { encoding: "utf8", flag: "wx" })
  renameSync(temporary, readmePath)
}

export function getDocsEnabledPromptMessage(): string {
  return "Enable docs output to disk?"
}

export function getDocsPathPromptMessage(): string {
  return "Docs output directory path (relative to project root):"
}

export function getDocHistoryModePromptMessage(): string {
  return "Docs history mode"
}
