import type { CommandRunner, CommandResult } from "./github-issues-readiness.js"
import type { GitHubIssuesWorkflowStateItem } from "./github-issues-mapping.js"

export interface GitHubIssueSnapshot {
  readonly number: number
  readonly title: string
  readonly state: "OPEN" | "CLOSED"
  readonly url: string | null
}

function parseIssueNumberFromUrl(urlValue: string): number | null {
  const match = /\/issues\/(\d+)\/?$/.exec(urlValue.trim())
  if (!match?.[1]) return null

  const issueNumber = Number(match[1])
  return Number.isInteger(issueNumber) ? issueNumber : null
}

function parseIssueView(value: string): GitHubIssueSnapshot | null {
  try {
    const parsed = JSON.parse(value) as unknown
    if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) return null

    const record = parsed as Record<string, unknown>
    const number = typeof record.number === "number" ? record.number : null
    const title = typeof record.title === "string" ? record.title : null
    const state = record.state === "OPEN" || record.state === "CLOSED" ? record.state : null
    const url = typeof record.url === "string" ? record.url : null

    if (number === null || title === null || state === null) return null

    return { number, title, state, url }
  } catch {
    return null
  }
}

function runRequiredCommand(
  execute: CommandRunner,
  cwd: string,
  command: string,
  args: readonly string[],
): CommandResult {
  return execute(command, args, cwd)
}

export function buildIssueBody(input: {
  readonly workflowId: string
  readonly planPath: string
  readonly localKey: string
  readonly title: string
}): string {
  return [
    "AI-generated by Wunderkind GitHub Issues workflow sync.",
    "",
    `Local workflow: ${input.planPath}`,
    `Workflow ID: ${input.workflowId}`,
    `Local key: ${input.localKey}`,
    "",
    `Source task: ${input.title}`,
  ].join("\n")
}

export function createRemoteIssue(
  execute: CommandRunner,
  cwd: string,
  repoSlug: string,
  issue: { readonly title: string; readonly body: string; readonly completed: boolean },
): GitHubIssuesWorkflowStateItem {
  const createResult = runRequiredCommand(
    execute,
    cwd,
    "gh",
    ["issue", "create", "--repo", repoSlug, "--title", issue.title, "--body", issue.body],
  )

  if (createResult.status !== 0) {
    throw new Error(`Failed to create GitHub issue: ${createResult.stderr || createResult.stdout}`)
  }

  const issueUrl = createResult.stdout.trim()
  const issueNumber = parseIssueNumberFromUrl(issueUrl)
  if (issueNumber === null) {
    throw new Error("Failed to parse GitHub issue number from `gh issue create` output.")
  }

  if (issue.completed) {
    const closeResult = runRequiredCommand(execute, cwd, "gh", ["issue", "close", `${issueNumber}`, "--repo", repoSlug])
    if (closeResult.status !== 0) {
      throw new Error(`Failed to close GitHub issue ${issueNumber}: ${closeResult.stderr || closeResult.stdout}`)
    }
  }

  return {
    localKey: "",
    title: issue.title,
    completed: issue.completed,
    issueNumber,
    issueId: null,
    issueUrl,
    lastSyncedTitle: issue.title,
    lastSyncedCompleted: issue.completed,
  }
}

export function readRemoteIssue(
  execute: CommandRunner,
  cwd: string,
  repoSlug: string,
  issueNumber: number,
): GitHubIssueSnapshot {
  const viewResult = runRequiredCommand(
    execute,
    cwd,
    "gh",
    ["issue", "view", `${issueNumber}`, "--repo", repoSlug, "--json", "number,title,state,url"],
  )

  if (viewResult.status !== 0) {
    throw new Error(`Failed to read GitHub issue ${issueNumber}: ${viewResult.stderr || viewResult.stdout}`)
  }

  const parsed = parseIssueView(viewResult.stdout)
  if (parsed === null) {
    throw new Error(`Failed to parse GitHub issue ${issueNumber} metadata.`)
  }

  return parsed
}

function assertRemoteIssueMatchesStateSnapshot(
  execute: CommandRunner,
  cwd: string,
  repoSlug: string,
  localKey: string,
  stateItem: GitHubIssuesWorkflowStateItem,
): void {
  const remote = readRemoteIssue(execute, cwd, repoSlug, stateItem.issueNumber)
  const expectedRemoteState = stateItem.lastSyncedCompleted ? "CLOSED" : "OPEN"

  if (remote.title !== stateItem.lastSyncedTitle || remote.state !== expectedRemoteState) {
    throw new Error(
      `Remote drift detected for local key ${localKey}. Resolve the GitHub issue manually before re-running workflow sync.`,
    )
  }
}

export function assertRemoteIssuesMatchState(
  execute: CommandRunner,
  cwd: string,
  repoSlug: string,
  stateItems: readonly GitHubIssuesWorkflowStateItem[],
): void {
  for (const stateItem of stateItems) {
    assertRemoteIssueMatchesStateSnapshot(execute, cwd, repoSlug, stateItem.localKey, stateItem)
  }
}

export function synchronizeRemoteIssue(
  execute: CommandRunner,
  cwd: string,
  repoSlug: string,
  localItem: { readonly localKey: string; readonly title: string; readonly completed: boolean },
  stateItem: GitHubIssuesWorkflowStateItem,
): GitHubIssuesWorkflowStateItem {
  assertRemoteIssueMatchesStateSnapshot(execute, cwd, repoSlug, localItem.localKey, stateItem)

  if (localItem.title !== stateItem.lastSyncedTitle) {
    const editResult = runRequiredCommand(
      execute,
      cwd,
      "gh",
      ["issue", "edit", `${stateItem.issueNumber}`, "--repo", repoSlug, "--title", localItem.title],
    )

    if (editResult.status !== 0) {
      throw new Error(`Failed to edit GitHub issue ${stateItem.issueNumber}: ${editResult.stderr || editResult.stdout}`)
    }
  }

  if (localItem.completed !== stateItem.lastSyncedCompleted) {
    const action = localItem.completed ? "close" : "reopen"
    const stateResult = runRequiredCommand(
      execute,
      cwd,
      "gh",
      ["issue", action, `${stateItem.issueNumber}`, "--repo", repoSlug],
    )

    if (stateResult.status !== 0) {
      throw new Error(`Failed to ${action} GitHub issue ${stateItem.issueNumber}: ${stateResult.stderr || stateResult.stdout}`)
    }
  }

  return {
    ...stateItem,
    title: localItem.title,
    completed: localItem.completed,
    lastSyncedTitle: localItem.title,
    lastSyncedCompleted: localItem.completed,
  }
}
